top_srcdir   = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
top_builddir = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
srcdir       = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/os
builddir     = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/os
VPATH        = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
