top_srcdir   = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
top_builddir = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
srcdir       = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/proxy
builddir     = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/proxy
VPATH        = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
