top_srcdir   = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
top_builddir = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
srcdir       = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/generators
builddir     = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/generators
VPATH        = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/generators

include $(top_srcdir)/build/special.mk

