top_srcdir   = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
top_builddir = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
srcdir       = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/server/mpm
builddir     = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/server/mpm
VPATH        = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
