top_srcdir   = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
top_builddir = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
srcdir       = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/filters
builddir     = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/filters
VPATH        = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/filters

include $(top_srcdir)/build/special.mk

