######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 21 20:06:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . test
INCLUDEPATH += . test

# Input
HEADERS += test/mydialog.h
FORMS += test/mydialog.ui
SOURCES += qt.cpp test/main.cpp test/mydialog.cpp
