top_srcdir   = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
top_builddir = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4
srcdir       = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/loggers
builddir     = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/loggers
VPATH        = /home/xwp/tao1/pycoming/net/test1/httpd-2.2.4/modules/loggers

include $(top_srcdir)/build/special.mk

