######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 21 20:06:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
FORMS += mydialog.ui
SOURCES += main.cpp mydialog.cpp
